lab4/lab4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("pharmacy/", include("pharmacy.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

lab4/pharmacy/urls.py
from django.urls import path

from . import views

app_name = "pharmacy"
urlpatterns = [
    # ex: /pharmacy/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /pharmacy/categories/
    path("categories/", views.CategoriesIndexView.as_view(), name="category_index"),
    # ex: /pharmacy/categories/5/
    path("categories/<int:pk>/", views.CategoriesDetailView.as_view(), name="category_detail"),
    # ex: /pharmacy/medicines/
    path("medicines/", views.MedicinesIndexView.as_view(), name="medicine_index"),
    # ex: /pharmacy/medicines/2/
    path("medicines/<int:pk>/", views.MedicinesDetailView.as_view(), name="medicine_detail"),
    # ex: /pharmacy/sales/
    path("sales/", views.SalesIndexView.as_view(), name="sale_index"),
    # ex: /pharmacy/sales/2/
    path("sales/<int:pk>/", views.SalesDetailView.as_view(), name="sale_detail"),
    # ex: /pharmacy/sales/add/
    path("sales/add/", views.SaleCreate.as_view(), name="sale_add"),
    # ex: /pharmacy/suppliers/
    path("suppliers/", views.SuppliersIndexView.as_view(), name="supplier_index"),
    # ex: /pharmacy/suppliers/2/
    path("suppliers/<int:pk>/", views.SuppliersDetailView.as_view(), name="supplier_detail"),
    # ex: /pharmacy/statistics/
    path("statistics/", views.StatisticsView.as_view(), name="statistics")
]

lab4/pharmacy/models.py
from datetime import datetime
from dateutil.relativedelta import relativedelta

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib import admin
import logging


logger = logging.getLogger('main')


class Supplier(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class MedicineCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Medicine(models.Model):
    name = models.CharField(max_length=50)
    instruction = models.CharField(max_length=200)
    description = models.CharField(max_length=100)
    price = models.IntegerField()
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    category = models.ForeignKey(MedicineCategory, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class PharmacyDepartment(models.Model):
    address = models.CharField(max_length=100)
    medicines = models.ManyToManyField(Medicine)

    class Meta:
        ordering = ["address"]

    def __str__(self):
        return self.address


class Sale(models.Model):
    date = models.DateTimeField("Date sold", default=datetime.now())
    ph_department = models.ForeignKey(PharmacyDepartment, on_delete=models.CASCADE)
    medicines = models.ManyToManyField(Medicine)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return self.date.__str__()

    def clean(self):
        try:
            if self.date > timezone.now():
                logger.error('Sale date error')
                raise ValidationError("Date is incorrect")
        except TypeError:
            logger.error('Can\'t convert input into date')
            raise ValidationError('Date is incorrect')


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey(PharmacyDepartment, on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField("Date of Birth", default=datetime.now() - relativedelta(years=18))

    def __str__(self):
        return f'{self.user.__str__()} in {self.department}'

    def clean(self):
        try:
            if timezone.now() - relativedelta(years=+18) < self.date_of_birth:  # i duno why it's working this way
                logger.error('Employee\'s age error')
                raise ValidationError("Come back when you're eighteen")
        except TypeError:
            logger.error('Can\'t convert input into date')
            raise ValidationError('Date is incorrect')

# logger = logging.getLogger(__name__)

lab4/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Pharmacy</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'pharmacy/css/styles.css' %}">
</head>

<body>

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                {% if user.is_authenticated %}
                <li>Welcome, {{ user.get_username }}</li>
                {% else %}
                <li>Unauthorized, <a href="{% url 'login'%}?next={{request.path}}">login</a></li>
                {% endif %}
                <li><a href="{% url 'pharmacy:index' %}">Home</a></li>
                <li><a href="{% url 'pharmacy:category_index' %}">Categories</a></li>
                <li><a href="{% url 'pharmacy:medicine_index' %}">Medicines</a></li>
                {% if perms.pharmacy.view_supplier %}
                <li><a href="{% url 'pharmacy:supplier_index' %}">Suppliers</a></li>
                {% endif %}
                {% if perms.pharmacy.view_sale %}
                <li><a href="{% url 'pharmacy:sale_index' %}">Sales</a></li>
                {% endif %}
                {% if perms.pharmacy.view_sale %}
                <li><a href="{% url 'pharmacy:statistics' %}">Statistics</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>
</body>
</html>