lab4/lab4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("pharmacy/", include("pharmacy.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

lab4/pharmacy/urls.py
from django.urls import path

from . import views

app_name = "pharmacy"
urlpatterns = [
    # ex: /pharmacy/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /pharmacy/categories/
    path("categories/", views.CategoriesIndexView.as_view(), name="category_index"),
    # ex: /pharmacy/categories/5/
    path("categories/<int:pk>/", views.CategoriesDetailView.as_view(), name="category_detail"),
    # ex: /pharmacy/medicines/
    path("medicines/", views.MedicinesIndexView.as_view(), name="medicine_index"),
    # ex: /pharmacy/medicines/2/
    path("medicines/<int:pk>/", views.MedicinesDetailView.as_view(), name="medicine_detail"),
    # ex: /pharmacy/sales/
    path("sales/", views.SalesIndexView.as_view(), name="sale_index"),
    # ex: /pharmacy/sales/2/
    path("sales/<int:pk>/", views.SalesDetailView.as_view(), name="sale_detail"),
    # ex: /pharmacy/sales/add/
    path("sales/add/", views.SaleCreate.as_view(), name="sale_add"),
    # ex: /pharmacy/suppliers/
    path("suppliers/", views.SuppliersIndexView.as_view(), name="supplier_index"),
    # ex: /pharmacy/suppliers/2/
    path("suppliers/<int:pk>/", views.SuppliersDetailView.as_view(), name="supplier_detail"),
    # ex: /pharmacy/statistics/
    path("statistics/", views.StatisticsView.as_view(), name="statistics")
]

lab4/pharmacy/models.py
from datetime import datetime
from dateutil.relativedelta import relativedelta

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib import admin
import logging


logger = logging.getLogger('main')


class Supplier(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class MedicineCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Medicine(models.Model):
    name = models.CharField(max_length=50)
    instruction = models.CharField(max_length=200)
    description = models.CharField(max_length=100)
    price = models.IntegerField()
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    category = models.ForeignKey(MedicineCategory, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class PharmacyDepartment(models.Model):
    address = models.CharField(max_length=100)
    medicines = models.ManyToManyField(Medicine)

    class Meta:
        ordering = ["address"]

    def __str__(self):
        return self.address


class Sale(models.Model):
    date = models.DateTimeField("Date sold", default=datetime.now())
    ph_department = models.ForeignKey(PharmacyDepartment, on_delete=models.CASCADE)
    medicines = models.ManyToManyField(Medicine)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return self.date.__str__()

    def clean(self):
        try:
            if self.date > timezone.now():
                logger.error('Sale date error')
                raise ValidationError("Date is incorrect")
        except TypeError:
            logger.error('Can\'t convert input into date')
            raise ValidationError('Date is incorrect')


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey(PharmacyDepartment, on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField("Date of Birth", default=datetime.now() - relativedelta(years=18))

    def __str__(self):
        return f'{self.user.__str__()} in {self.department}'

    def clean(self):
        try:
            if timezone.now() - relativedelta(years=+18) < self.date_of_birth:  # i duno why it's working this way
                logger.error('Employee\'s age error')
                raise ValidationError("Come back when you're eighteen")
        except TypeError:
            logger.error('Can\'t convert input into date')
            raise ValidationError('Date is incorrect')

# logger = logging.getLogger(__name__)

lab4/pharmacy/views.py
import logging
from datetime import datetime
import requests

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import MedicineCategory, Medicine, Supplier, Sale
from .helpers import plot_last_days_sales


logger = logging.getLogger('main')


class IndexView(generic.DetailView):
    logger.warning('in index view')
    template_name = "pharmacy/index.html"
    joke_info = {}
    model = joke_info

    def get(self, request, *args, **kwargs):
        logger.info('In index view')

        url = 'https://official-joke-api.appspot.com/jokes/programming/random'
        joke_info = requests.get(url).json()
        self.joke_info = joke_info
        logger.debug(joke_info)
        context = get_ip_request()
        logger.debug(f'context: {context}')

        return render(request, self.template_name, context)


def get_ip_request():
    logger.info('connecting to the joke API')
    url = 'https://official-joke-api.appspot.com/jokes/programming/random'
    ip_request = requests.get(url).json()
    ip_request = ip_request[0]
    setup = ip_request['setup']
    punchline = ip_request['punchline']
    logger.debug(ip_request)
    return {'setup': setup, 'punchline': punchline}


class CategoriesIndexView(generic.ListView):
    template_name = "pharmacy/categories_index.html"
    context_object_name = "categories_list"

    def get_queryset(self):
        """
        Return the categories
        """
        return MedicineCategory.objects.order_by("-name")

    def get(self, request, *args, **kwargs):
        logger.info('In categories index view')
        return super().get(request, *args, **kwargs)


class CategoriesDetailView(generic.DetailView):
    model = MedicineCategory
    template_name = "pharmacy/categories_detail.html"

    def get(self, request, *args, **kwargs):
        logger.info('In categories detail view')
        return super().get(request, *args, **kwargs)


class MedicinesIndexView(generic.ListView):
    template_name = "pharmacy/medicines_index.html"
    context_object_name = "medicines_list"

    def get_queryset(self):
        """
        Return the medicines
        """
        return Medicine.objects.order_by("-name")

    def get(self, request, *args, **kwargs):
        logger.info('In medicines index view')
        return super().get(request, *args, **kwargs)


class MedicinesDetailView(generic.DetailView):
    model = Medicine
    template_name = "pharmacy/medicines_detail.html"

    def get(self, request, *args, **kwargs):
        logger.info('In medicines detail view')
        return super().get(request, *args, **kwargs)


class SalesIndexView(PermissionRequiredMixin, generic.ListView):
    logger.info('In sales index view')
    permission_required = 'pharmacy.view_sale'
    template_name = "pharmacy/sales_index.html"
    context_object_name = "sales_list"

    def get_queryset(self):
        """
        Return the sales
        """
        return Sale.objects.order_by("-date")

    def get(self, request, *args, **kwargs):
        logger.info('In sales index view')
        return super().get(request, *args, **kwargs)


class SalesDetailView(PermissionRequiredMixin, generic.DetailView):
    permission_required = 'pharmacy.view_sale'
    model = Sale
    template_name = "pharmacy/sales_detail.html"

    def get(self, request, *args, **kwargs):
        logger.info('In sales detail view')
        return super().get(request, *args, **kwargs)


class SuppliersIndexView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'pharmacy.view_supplier'
    template_name = "pharmacy/suppliers_index.html"
    context_object_name = "suppliers_list"

    def get_queryset(self):
        """
        Return the suppliers
        """
        return Supplier.objects.order_by("-name")

    def get(self, request, *args, **kwargs):
        logger.info('In suppliers index view')
        return super().get(request, *args, **kwargs)


class SuppliersDetailView(PermissionRequiredMixin, generic.DetailView):
    permission_required = 'pharmacy.view_supplier'
    model = Supplier
    template_name = "pharmacy/suppliers_detail.html"

    def get(self, request, *args, **kwargs):
        logger.info('In suppliers detail view')
        return super().get(request, *args, **kwargs)


class SaleCreate(PermissionRequiredMixin, generic.CreateView):
    permission_required = 'pharmacy.add_sale'
    model = Sale
    fields = '__all__'
    initial = {'date': datetime.now(), }
    template_name = "pharmacy/sales_add.html"
    success_url = reverse_lazy('pharmacy:sale_index')

    def get(self, request, *args, **kwargs):
        logger.info('In sales add view')
        return super().get(request, *args, **kwargs)


class StatisticsView(PermissionRequiredMixin, generic.ListView):
    context_object_name = 'sales_list'
    permission_required = 'pharmacy.view_sale'
    template_name = 'pharmacy/statistics.html'

    def get(self, request, *args, **kwargs):
        logger.info('In statistics view')
        plot_last_days_sales()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        """
        Return the sales
        """
        return Sale.objects.order_by("-date")

lab4/pharmacy/templates/pharmacy/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Pharmacy</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'pharmacy/css/styles.css' %}">
</head>

<body>

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'pharmacy:index' %}">Home</a></li>
                <li><a href="{% url 'pharmacy:category_index' %}">Categories</a></li>
                <li><a href="{% url 'pharmacy:medicine_index' %}">Medicines</a></li>
                <li><a href="{% url 'pharmacy:supplier_index' %}">Suppliers</a></li>
                <li><a href="{% url 'pharmacy:sale_index' %}">Sales</a></li>
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>
</body>
</html>

lab4/pharmacy/templates/pharmacy/categories_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ medicinecategory.name }}</h1>
{% if medicinecategory.medicine_set.all %}
<ul>
    {% for medicine in medicinecategory.medicine_set.all %}
    <li><a href="{% url 'pharmacy:medicine_detail' medicine.id %}">{{ medicine.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No medicines are available.</p>
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/categories_index.html
{% extends "base.html" %}

{% block content %}
{% if categories_list %}
<ul>
    {% for category in categories_list %}
    <li><a href="{% url 'pharmacy:category_detail' category.id %}">{{ category.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No categories are available.</p>
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/index.html
{% extends "base.html" %}

{% block content %}
<h1>Pharmacy homepage</h1>
<!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
<div id="player"></div>

<script>
    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var player;
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '360',
            width: '640',
            videoId: 'e-c8KjFmcJ4',
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    // 4. The API will call this function when the video player is ready.
    function onPlayerReady(event) {
        event.target.playVideo();
    }

    // 5. The API calls this function when the player's state changes.
    //    The function indicates that when playing a video (state=1),
    //    the player should play for six seconds and then stop.
    var done = false;
    function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
            player.seekTo(3);
            done = true;
        }
    }
    function stopVideo() {
        player.stopVideo();
    }
</script>
<h2>{{ setup }}</h2>
<h3>{{ punchline }}</h3>
{% endblock %}

lab4/pharmacy/templates/pharmacy/medicines_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ medicine.name }}</h1>
<p>Category: {{ medicine.category }}</p>
<p>Price: {{ medicine.price }}</p>
<p>Supplier: {{ medicine.supplier.name }}</p>
<h3>Description:</h3>
<p>{{ medicine.description }}</p>
<h3>Instruction:</h3>
<p>{{ medicine.instruction }}</p>
{% endblock %}

lab4/pharmacy/templates/pharmacy/medicines_index.html
{% extends "base.html" %}

{% block content %}
{% if medicines_list %}
<ul>
    {% for medicine in medicines_list %}
    <li><a href="{% url 'pharmacy:medicine_detail' medicine.id %}">{{ medicine.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No medicines are available.</p>
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/sales_add.html
{% extends "base.html" %}

{% block content %}
<h1>Fill the information</h1>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

lab4/pharmacy/templates/pharmacy/sales_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ sale.date }}</h1>
<p>Pharmacy department: {{ sale.ph_department }}</p>
<h3>Medicines:</h3>
{% if sale.medicines.all %}
<ul>
    {% for medicine in sale.medicines.all %}
    <li><a href="{% url 'pharmacy:medicine_detail' medicine.id %}">{{ medicine.name }} - {{ medicine.price }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No medicines are available.</p>
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/sales_index.html
{% extends "base.html" %}

{% block content %}
{% if perms.pharmacy.add_sale %}
<h3><a href="{% url 'pharmacy:sale_add' %}">Make a sell</a></h3>
{% endif %}
{% if sales_list %}
<ul>
    {% for sale in sales_list %}
    <li><a href="{% url 'pharmacy:sale_detail' sale.id %}">{{ sale.date }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No sales are available.</p>
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/statistics.html
{% extends "base.html" %}

{% block content %}
{% if perms.pharmacy.add_sale %}
<h1>Statistics page</h1>
{% load static %}
<img src="{% static 'pharmacy/images/plot.png' %}" class="img-thumbnail" alt="...">
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/suppliers_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ supplier.name }}</h1>
{% if supplier.medicine_set.all %}
<ul>
    {% for medicine in supplier.medicine_set.all %}
    <li><a href="{% url 'pharmacy:medicine_detail' medicine.id %}">{{ medicine.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No medicines are available.</p>
{% endif %}
{% endblock %}

lab4/pharmacy/templates/pharmacy/suppliers_index.html
{% extends "base.html" %}

{% block content %}
{% if suppliers_list %}
<ul>
    {% for supplier in suppliers_list %}
    <li><a href="{% url 'pharmacy:supplier_detail' supplier.id %}">{{ supplier.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No suppliers are available.</p>
{% endif %}
{% endblock %}